global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['localhost:8000']  # Use localhost since containers can reach host
    metrics_path: '/metrics'
    scrape_interval: 5s
